title: Only-MC STATUS SERWERÓW
languageCode: pl
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: Ta strona stanu zawiera aktualne informacje na temat
    normalnego działania naszych systemów, możliwych incydentów i ich
    rozwiązania.
  systems:
    - name: Website
      description: Our company public facing website
      link: https://www.example.com/
    - name: Helpdesk
      description: Our company customer support site
      link: https://support.example.com/
  dateFormat: January 2, 2006 O 3:04 PM
  disqusShortname: ONLy-MC
  timezoneString: " UTC"
  logo: /images/clearstatus.svg
  description_header: Ta strona zawiera najpotrzebniejsze informacje o poprawności
    działania naszych systemów. Jeżeli masz jakieś problemy (np. z połączeniem z
    serwerem) wróć tu z powrotem i zobacz czy wszystko działa poprawnie
  copyrightHolder: ONLY-MC.PL 2021
  eventsPerPage: 10
  iconType: image/png
  icon: /images/clearstatus.png
  description_footer: Ta strona powstała w celach informacyjnych. Została ona
    wykonana na zlecenie przez DJDIAGUUU
