title: Only-MC STATUS SERWERÓW
baseURL: https://only-mc.pl/
languageCode: pl
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: Ta strona stanu zawiera aktualne informacje na temat
    normalnego działania naszych systemów, możliwych incydentów i ich
    rozwiązania.
  systems:
    - name: Strona WWW
      description: Nasza strona WWW
      link: https://only-mc.pl/
    - name: Formularz kontaktowy
      description: Nasz formularz kontaktowy
      link: https://only-mc.pl/kontakt
    - name: ItemShop
      description: Nasz sklepik
      link: https://only-mc.pl/sklep/
    - name: Lista banów
      description: Lista kar nadanych na naszych serwerach
      link: https://bany.only-mc.pl/
    - name: Discord
      description: Nasz discord
      link: https://discord.only-mc.pl/
    - name: "Bot #1"
      description: "Nasz bot na discord #1"
    - name: "Bot #1"
      description: "Nasz bot na discord #1"
    - name: Serwer Minecraft
      description: Oto nasz serwer minecraft Survival
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: ONLy-MC
  timezoneString: " UTC"
  logo: static/images/uploads/images.jpg
  description_header: Ta strona zawiera najpotrzebniejsze informacje o poprawności
    działania naszych systemów. Jeżeli masz jakieś problemy (np. z połączeniem z
    serwerem) wróć tu z powrotem i zobacz czy wszystko działa poprawnie
  copyrightHolder: ONLY-MC.PL 2021
  eventsPerPage: 10
  iconType: image/png
  icon: /images/clearstatus.png
  description_footer: Ta strona powstała w celach informacyjnych. Została ona
    wykonana na zlecenie przez DJDIAGUUU
